# Generated by Django 5.0.3 on 2024-04-13 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='images',
            new_name='image',
        ),
    ]
