# Generated by Django 5.0.3 on 2024-04-07 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_alter_facility_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='open_hours',
        ),
    ]
