# Generated by Django 5.0.3 on 2024-04-07 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0004_rename_ratings_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OpenHours',
        ),
    ]
